import type { Message } from "../../components/chat/ChatContent";

export const dummyMessages: Message[] = [
  {
    id: 1,
    session_id: 101,
    message: "안녕하세요!",
    sender: "user",
    is_important: false,
    timestamp: "2025-09-29T09:00:00Z",
  },
  {
    id: 2,
    session_id: 101,
    message: "안녕하세요! 무엇을 도와드릴까요?",
    sender: "ai",
    is_important: false,
    timestamp: "2025-09-29T09:00:03Z",
  },
  {
    id: 3,
    session_id: 101,
    message: "오늘 날씨가 어떤가요?",
    sender: "user",
    is_important: false,
    timestamp: "2025-09-29T09:01:10Z",
  },
  {
    id: 4,
    session_id: 101,
    message: "오늘은 맑고 기온은 23도입니다.",
    sender: "ai",
    is_important: true,
    timestamp: "2025-09-29T09:01:15Z",
  },
  {
    id: 5,
    session_id: 101,
    message: "고마워요!",
    sender: "user",
    is_important: false,
    timestamp: "2025-09-29T09:02:20Z",
  },
  {
    id: 6,
    session_id: 102,
    message:
      "새로운 세션을 시작합니다.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    sender: "ai",
    is_important: false,
    timestamp: "2025-09-29T09:05:00Z",
  },
  {
    id: 7,
    session_id: 102,
    message: "React 프로젝트를 설정하는 방법 알려주세요.",
    sender: "user",
    is_important: true,
    timestamp: "2025-09-29T09:06:10Z",
  },
  {
    id: 8,
    session_id: 102,
    message: "npx create-react-app 명령어로 시작할 수 있습니다.",
    sender: "ai",
    is_important: true,
    timestamp: "2025-09-29T09:06:25Z",
  },
  {
    id: 9,
    session_id: 102,
    message: "TypeScript로 설정하려면 어떻게 해야 하나요?",
    sender: "user",
    is_important: false,
    timestamp: "2025-09-29T09:07:10Z",
  },
  {
    id: 10,
    session_id: 102,
    message: "npx create-react-app my-app --template typescript 로 실행하세요.",
    sender: "ai",
    is_important: true,
    timestamp: "2025-09-29T09:07:40Z",
  },
  {
    id: 11,
    session_id: 103,
    message: "zustand 사용법 좀 알려주세요.",
    sender: "user",
    is_important: true,
    timestamp: "2025-09-29T09:15:00Z",
  },
  {
    id: 12,
    session_id: 103,
    message: "zustand는 간단한 상태 관리 라이브러리예요.",
    sender: "ai",
    is_important: false,
    timestamp: "2025-09-29T09:15:10Z",
  },
  {
    id: 13,
    session_id: 103,
    message: "예시 코드 보여줄 수 있나요?",
    sender: "user",
    is_important: false,
    timestamp: "2025-09-29T09:15:40Z",
  },
  {
    id: 14,
    session_id: 103,
    message: "create 함수로 스토어를 만들고 훅처럼 사용할 수 있습니다.",
    sender: "ai",
    is_important: true,
    timestamp: "2025-09-29T09:16:00Z",
  },
  {
    id: 15,
    session_id: 103,
    message: "좋네요. socket.io랑 같이 사용할 수 있을까요?",
    sender: "user",
    is_important: false,
    timestamp: "2025-09-29T09:16:40Z",
  },
  {
    id: 16,
    session_id: 103,
    message:
      "네, socket.io에서 수신한 이벤트를 zustand state로 업데이트하면 됩니다.",
    sender: "ai",
    is_important: true,
    timestamp: "2025-09-29T09:16:55Z",
  },
  {
    id: 17,
    session_id: 104,
    message: "로그인 기능 구현하려고 합니다.",
    sender: "user",
    is_important: false,
    timestamp: "2025-09-29T09:20:00Z",
  },
  {
    id: 18,
    session_id: 104,
    message:
      "로그인은 API 요청을 zustand와 연결해서 token 상태를 관리하면 편리합니다.",
    sender: "ai",
    is_important: true,
    timestamp: "2025-09-29T09:20:30Z",
  },
  {
    id: 19,
    session_id: 104,
    message: "좋습니다, 감사합니다!",
    sender: "user",
    is_important: false,
    timestamp: "2025-09-29T09:21:00Z",
  },
  {
    id: 20,
    session_id: 104,
    message: "언제든지 도와드리겠습니다.",
    sender: "ai",
    is_important: false,
    timestamp: "2025-09-29T09:21:10Z",
  },
];
