name: Prod Deploy
on:
    push:
        branches:
            - main

jobs:
    my-deploy:
        runs-on: ubuntu-latest

        env:
            VITE_API_URL: ${{ secrets.VITE_API_URL }}

        steps:
            - name: github repository 파일 불러오기
              uses: actions/checkout@v4

            - name: 의존성 설치
              run: npm i

            - name: 빌드하기
              run: npm run build

            - name: aws 인증
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-region: ap-northeast-2
                  aws-access-key-id: ${{secrets.PROD_AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{secrets.PROD_AWS_SECRET_ACCESS_KEY }}

            - name: s3 파일들 전체 삭제 후 업로드
              run: |
                  aws s3 rm --recursive s3://${{ secrets.PROD_S3_BUCKET_NAME }}
                  aws s3 cp ./dist/ s3://${{ secrets.PROD_S3_BUCKET_NAME }}/ --recursive

            - name: 클라우드프론트 캐시 무효화
              run: aws cloudfront create-invalidation --distribution-id ${{ secrets.PROD_DISTRIBUTION_ID }} --paths "/*"
